/**
 * @tenant/cpi
 *
 * The pinned CPI snapshot, as data. This package exists so that `@tenant/rules` can stay
 * a pure function with no notion of where its numbers came from: the engine takes a
 * snapshot as an argument, and this is where the real one lives. ADR-0003, ADR-0005.
 *
 * The engine must never import this package. That direction is the whole point.
 *
 * The JSON is generated by `scripts/build_cpi_snapshot.py` from CSO PxStat table CPM24,
 * statistic CPM24C01, sub index CP00, which is the series the RTB names on its own
 * calculator page. Updating it is a pull request with a visible diff, not a background
 * fetch, and CI fails when the CSO publishes a month this file does not have.
 */

import type { CpiSnapshot } from "@tenant/rules";
import raw from "../../../data/cpi/cpi-all-items.json";

export interface CpiProvenance {
  readonly source: string;
  readonly table: string;
  readonly statistic: string;
  readonly subIndex: string;
  readonly url: string;
  readonly datasetUpdated: string;
  readonly whyThisSeries: string;
}

/**
 * Validate at load rather than trusting the file.
 *
 * The snapshot is generated, so in normal operation this never fails. It fails loudly if
 * someone hand-edits the JSON or the generator changes shape, which is exactly when a
 * silent wrong answer would be most expensive.
 */
function validate(input: typeof raw): CpiSnapshot {
  if (typeof input.sha256 !== "string" || input.sha256.length === 0) {
    throw new Error("CPI snapshot has no sha256");
  }
  if (!Array.isArray(input.series) || input.series.length === 0) {
    throw new Error("CPI snapshot has no series");
  }

  let previous = "";
  for (const row of input.series) {
    if (!/^\d{4}-\d{2}$/.test(row.month)) {
      throw new Error(`CPI snapshot has a bad month: ${row.month}`);
    }
    if (typeof row.value !== "number" || !Number.isFinite(row.value) || row.value <= 0) {
      throw new Error(`CPI snapshot has a bad value at ${row.month}: ${row.value}`);
    }
    if (row.month <= previous) {
      throw new Error(`CPI snapshot is not in ascending month order at ${row.month}`);
    }
    previous = row.month;
  }

  // The generator writes snake_case, which is the convention for the JSON artifact and
  // for the Python freshness check that also reads it. The mapping happens here, once.
  const last = input.series[input.series.length - 1];
  if (last === undefined || last.month !== input.latest_month) {
    throw new Error(
      `CPI snapshot latest_month ${input.latest_month} does not match the last row ${last?.month}`,
    );
  }

  return {
    sha256: input.sha256,
    base: input.base,
    latestMonth: input.latest_month,
    series: input.series,
  };
}

/** The pinned snapshot. Pass this to `evaluateRent`. */
export const CPI_SNAPSHOT: CpiSnapshot = validate(raw);

export const CPI_PROVENANCE: CpiProvenance = {
  source: raw.provenance.source,
  table: raw.provenance.table,
  statistic: raw.provenance.statistic,
  subIndex: raw.provenance.sub_index,
  url: raw.provenance.url,
  datasetUpdated: raw.provenance.dataset_updated,
  whyThisSeries: raw.provenance.why_this_series,
};
