/**
 * @tenant/cpi
 *
 * The pinned CPI snapshot, as data. This package exists so that `@tenant/rules` can stay
 * a pure function with no notion of where its numbers came from: the engine takes a
 * snapshot as an argument, and this is where the real one lives. ADR-0003, ADR-0005.
 *
 * The engine must never import this package. That direction is the whole point.
 *
 * The JSON is generated by `scripts/build_cpi_snapshot.py` from CSO PxStat table CPM24,
 * statistic CPM24C01, sub index CP00, which is the series the RTB names on its own
 * calculator page. Updating it is a pull request with a visible diff, not a background
 * fetch, and CI fails when the CSO publishes a month this file does not have.
 */

import type { CpiSnapshot } from "@tenant/rules";
import raw from "../../../data/cpi/cpi-all-items.json";
import hicpRaw from "../../../data/cpi/hicp-all-items.json";

/**
 * The shape the generator writes.
 *
 * Declared structurally rather than as `typeof raw`, because inferring it from one of the
 * two JSON files pins literal types that the other does not match. `fetched_at` is null in a
 * snapshot rebuilt from a saved response and a string in one fetched live, and the compiler
 * was right to complain about that.
 */
interface RawSnapshot {
  readonly schema: number;
  readonly sha256: string;
  readonly base: string;
  readonly latest_month: string;
  readonly count: number;
  readonly series: readonly { readonly month: string; readonly value: number }[];
  readonly provenance: {
    readonly source: string;
    readonly table: string;
    readonly statistic: string;
    readonly statistic_label: string;
    readonly sub_index: string;
    readonly sub_index_label: string;
    readonly url: string;
    readonly dataset_updated: string;
    readonly fetched_at: string | null;
    readonly why_this_series: string;
  };
}

export interface CpiProvenance {
  readonly source: string;
  readonly table: string;
  readonly statistic: string;
  readonly subIndex: string;
  readonly url: string;
  readonly datasetUpdated: string;
  readonly whyThisSeries: string;
}

/**
 * Validate at load rather than trusting the file.
 *
 * The snapshot is generated, so in normal operation this never fails. It fails loudly if
 * someone hand-edits the JSON or the generator changes shape, which is exactly when a
 * silent wrong answer would be most expensive.
 */
function validate(input: RawSnapshot): CpiSnapshot {
  if (typeof input.sha256 !== "string" || input.sha256.length === 0) {
    throw new Error("CPI snapshot has no sha256");
  }
  if (!Array.isArray(input.series) || input.series.length === 0) {
    throw new Error("CPI snapshot has no series");
  }

  let previous = "";
  for (const row of input.series) {
    if (!/^\d{4}-\d{2}$/.test(row.month)) {
      throw new Error(`CPI snapshot has a bad month: ${row.month}`);
    }
    if (typeof row.value !== "number" || !Number.isFinite(row.value) || row.value <= 0) {
      throw new Error(`CPI snapshot has a bad value at ${row.month}: ${row.value}`);
    }
    if (row.month <= previous) {
      throw new Error(`CPI snapshot is not in ascending month order at ${row.month}`);
    }
    previous = row.month;
  }

  // The generator writes snake_case, which is the convention for the JSON artifact and
  // for the Python freshness check that also reads it. The mapping happens here, once.
  const last = input.series[input.series.length - 1];
  if (last === undefined || last.month !== input.latest_month) {
    throw new Error(
      `CPI snapshot latest_month ${input.latest_month} does not match the last row ${last?.month}`,
    );
  }

  return {
    sha256: input.sha256,
    base: input.base,
    latestMonth: input.latest_month,
    series: input.series,
  };
}

/** The pinned CPI snapshot. Pass this to `evaluateRent`. */
export const CPI_SNAPSHOT: CpiSnapshot = validate(raw);

/**
 * The pinned HICP snapshot, for the pre-2026 regime.
 *
 * Section 19(6) keeps that regime alive for any rent review notice served before
 * 1 March 2026, and it used HICP rather than CPI. Section 6 of the Residential Tenancies
 * (No. 2) Act 2021 defines HICP values as the All-Items Harmonised Index of Consumer Prices
 * for Ireland published by the CSO under Regulation (EU) 2016/792, which is CPM23C01/CP00.
 */
export const HICP_SNAPSHOT: CpiSnapshot = validate(hicpRaw);

function provenanceOf(input: RawSnapshot): CpiProvenance {
  return {
    source: input.provenance.source,
    table: input.provenance.table,
    statistic: input.provenance.statistic,
    subIndex: input.provenance.sub_index,
    url: input.provenance.url,
    datasetUpdated: input.provenance.dataset_updated,
    whyThisSeries: input.provenance.why_this_series,
  };
}

export const CPI_PROVENANCE: CpiProvenance = provenanceOf(raw);
export const HICP_PROVENANCE: CpiProvenance = provenanceOf(hicpRaw);
